logging:
  level:
    root: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

spring:
  # BBDD embebida H2 en memoria
  h2:
    console:
      enabled: true  # Habilitar la consola de H2
      path: /h2-console  # Ruta de acceso a la consola
      settings:
        web-allow-others: true  # Permitir acceso a la consola desde otras IPs
  #H2
  datasource:
    datasource-initializer-enabled: true
    jdbcUrl: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false;
    username: sa
    password: password
    driverClassName: org.h2.Driver
    minimum-idle: 5
    maximum-pool-size: 20
    auto-commit: true
    idle-timeout: 600000
    max-lifetime: 1800000
    connection-timeout: 30000
    hikari:
      connection-test-query: SELECT 1
    poolName: HikariCP-Principal
  # Configuración JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true  # Muestra las consultas SQL en la consola
    open-in-view: false  # Evitar problemas de rendimiento en producción