logging:
  level:
    root: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

spring:
  # SQL Server
  datasource:
    datasource-initializer-enabled: false
    minimum-idle: 5
    maximum-pool-size: 20
    auto-commit: true
    idle-timeout: 600000
    max-lifetime: 1800000
    connection-timeout: 30000
    hikari:
      connection-test-query: SELECT 1
    jdbcUrl: jdbc:sqlserver://BI-DEVELOP.lvi.lan:1433;databaseName=AUTOLINE;encrypt=true;trustServerCertificate=true;
    username: APP_autoline
    password: 'u7WVIsizOUdL'
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    poolName: HikariCP-Principal

  # Configuración JPA
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true  # Muestra las consultas SQL en la consola
    open-in-view: false  # Evitar problemas de rendimiento en producción
